export interface WalletInfo {
  id: string;
  name: string;
  shortName: string;
  color: string;
  installUrl: string;
  /** Property on the provider object to detect it */
  detectKey?: string;
  /** Property on window to detect it */
  windowKey?: string;
  /** Check function for complex detection */
  detectFn?: (provider: any) => boolean;
}

/**
 * Registro de 100+ wallets EVM con datos de detección e instalación.
 * Cada wallet tiene un color de marca, URL de instalación y claves de detección.
 */
export const WALLET_REGISTRY: WalletInfo[] = [
  // ── Top 10 ──────────────────────────────
  {
    id: "metamask",
    name: "MetaMask",
    shortName: "MM",
    color: "#E2761B",
    installUrl: "https://metamask.io/download/",
    detectKey: "isMetaMask",
  },
  {
    id: "trustwallet",
    name: "Trust Wallet",
    shortName: "TW",
    color: "#3375BB",
    installUrl: "https://trustwallet.com/download",
    detectKey: "isTrust",
    windowKey: "trustwallet",
  },
  {
    id: "coinbase",
    name: "Coinbase Wallet",
    shortName: "CB",
    color: "#0052FF",
    installUrl: "https://www.coinbase.com/wallet/downloads",
    detectKey: "isCoinbaseWallet",
    windowKey: "coinbaseWalletExtension",
  },
  {
    id: "okx",
    name: "OKX Wallet",
    shortName: "OKX",
    color: "#000000",
    installUrl: "https://www.okx.com/web3",
    detectKey: "isOKExWallet",
  },
  {
    id: "bitget",
    name: "Bitget Wallet",
    shortName: "BG",
    color: "#00F0FF",
    installUrl: "https://www.bitget.com/web3",
    detectKey: "isBitKeep",
  },
  {
    id: "bybit",
    name: "Bybit Wallet",
    shortName: "BY",
    color: "#F7A600",
    installUrl: "https://www.bybit.com/en/web3",
    detectKey: "isBybitWallet",
  },
  {
    id: "phantom",
    name: "Phantom",
    shortName: "PH",
    color: "#AB9FF2",
    installUrl: "https://phantom.app/download",
    detectKey: "isPhantom",
  },
  {
    id: "rabby",
    name: "Rabby Wallet",
    shortName: "RB",
    color: "#7C7AF7",
    installUrl: "https://rabby.io/",
    detectKey: "isRabby",
  },
  {
    id: "onekey",
    name: "OneKey Wallet",
    shortName: "1K",
    color: "#FFD600",
    installUrl: "https://onekey.so/download",
    detectKey: "isOneKey",
  },
  {
    id: "tally",
    name: "Tally Ho",
    shortName: "TH",
    color: "#FF6154",
    installUrl: "https://tally.cash/",
    detectKey: "isTally",
  },

  // ── 11-30 ───────────────────────────────
  {
    id: "rainbow",
    name: "Rainbow",
    shortName: "RBW",
    color: "#E8793A",
    installUrl: "https://rainbow.me/",
    detectKey: "isRainbow",
  },
  {
    id: "zerion",
    name: "Zerion",
    shortName: "ZE",
    color: "#3CEFA3",
    installUrl: "https://zerion.io/download",
    detectKey: "isZerion",
  },
  {
    id: "frame",
    name: "Frame",
    shortName: "FR",
    color: "#FF6B4A",
    installUrl: "https://frame.sh/",
    detectKey: "isFrame",
  },
  {
    id: "core",
    name: "Core Wallet",
    shortName: "CORE",
    color: "#1E1E1E",
    installUrl: "https://core.app/",
    detectKey: "isAvalanche",
  },
  {
    id: "backpack",
    name: "Backpack",
    shortName: "BP",
    color: "#E879F9",
    installUrl: "https://backpack.app/download",
    detectKey: "isBackpack",
  },
  {
    id: "xdefi",
    name: "XDEFI Wallet",
    shortName: "XD",
    color: "#1BCEA0",
    installUrl: "https://www.xdefi.io/",
    detectKey: "isXDEFI",
  },
  {
    id: "krystal",
    name: "Krystal",
    shortName: "KZ",
    color: "#6C5CE7",
    installUrl: "https://krystal.app/",
    detectKey: "isKrystal",
  },
  {
    id: "taho",
    name: "Taho (Tally)",
    shortName: "TA",
    color: "#7B61FF",
    installUrl: "https://taho.xyz/",
    detectKey: "isTaho",
  },
  {
    id: "mathwallet",
    name: "MathWallet",
    shortName: "MW",
    color: "#36B049",
    installUrl: "https://www.mathwallet.org/",
    detectKey: "isMathWallet",
  },
  {
    id: "tokenpocket",
    name: "TokenPocket",
    shortName: "TP",
    color: "#3B7CFF",
    installUrl: "https://www.tokenpocket.pro/",
    detectKey: "isTokenPocket",
  },

  // ── 31-50 ───────────────────────────────
  {
    id: "coin98",
    name: "Coin98 Wallet",
    shortName: "C98",
    color: "#6E3AFF",
    installUrl: "https://coin98.com/wallet",
    detectKey: "isCoin98",
  },
  {
    id: "gatewallet",
    name: "Gate Wallet",
    shortName: "GT",
    color: "#2EA44F",
    installUrl: "https://www.gate.io/web3",
    detectKey: "isGate",
  },
  {
    id: "wombat",
    name: "Wombat Wallet",
    shortName: "WB",
    color: "#4CB8E0",
    installUrl: "https://wombat.app/",
    detectKey: "isWombatWallet",
  },
  {
    id: "marswallet",
    name: "Mars Wallet",
    shortName: "MR",
    color: "#FF4D4D",
    installUrl: "https://marswallet.io/",
    detectKey: "isMarsWallet",
  },
  {
    id: "manta",
    name: "Manta Wallet",
    shortName: "MN",
    color: "#1BCEA0",
    installUrl: "https://www.manta.network/wallet",
    detectKey: "isManta",
  },
  {
    id: "ontowallet",
    name: "ONTO Wallet",
    shortName: "ON",
    color: "#00B4D8",
    installUrl: "https://onto.app/",
    detectKey: "isONTO",
  },
  {
    id: "defiwallet",
    name: "DeFi Wallet",
    shortName: "DF",
    color: "#35BAD2",
    installUrl: "https://crypto.com/wallet",
    detectKey: "isDeFiWallet",
  },
  {
    id: "nifty",
    name: "Nifty Wallet",
    shortName: "NF",
    color: "#6DC5A3",
    installUrl: "https://www.poa.network/",
    detectKey: "isNiftyWallet",
  },
  {
    id: "blockwallet",
    name: "BlockWallet",
    shortName: "BLK",
    color: "#3D3D3D",
    installUrl: "https://blockwallet.io/",
    detectKey: "isBlockWallet",
  },
  {
    id: " frontier",
    name: "Frontier Wallet",
    shortName: "FRT",
    color: "#2B6CB0",
    installUrl: "https://frontier.xyz/",
    detectKey: "isFrontier",
  },

  // ── 51-70 ───────────────────────────────
  {
    id: "myetherwallet",
    name: "MyEtherWallet",
    shortName: "MEW",
    color: "#F6851B",
    installUrl: "https://www.myetherwallet.com/",
    detectKey: "isMEWwallet",
  },
  {
    id: "coinomo",
    name: "Coinomo",
    shortName: "CM",
    color: "#5B4CFF",
    installUrl: "https://coinomo.com/",
    detectKey: "isCoinomo",
  },
  {
    id: "dodo",
    name: "DODO Wallet",
    shortName: "DD",
    color: "#3366FF",
    installUrl: "https://dodoex.io/",
    detectKey: "isDODO",
  },
  {
    id: "kyberswap",
    name: "KyberSwap Wallet",
    shortName: "KS",
    color: "#23292F",
    installUrl: "https://kyberswap.com/",
    detectKey: "isKyberSwapWallet",
  },
  {
    id: "halo",
    name: "Halo Wallet",
    shortName: "HL",
    color: "#6C5CE7",
    installUrl: "https://halowallet.io/",
    detectKey: "isHalo",
  },
  {
    id: "bitski",
    name: "Bitski",
    shortName: "BS",
    color: "#6762FF",
    installUrl: "https://www.bitski.com/",
    detectKey: "isBitski",
  },
  {
    id: "atoken",
    name: "AToken",
    shortName: "AT",
    color: "#3B82F6",
    installUrl: "https://www.atoken.com/",
    detectKey: "isAToken",
  },
  {
    id: "zeffy",
    name: "Zeffy",
    shortName: "ZF",
    color: "#00D4AA",
    installUrl: "https://zeffy.io/",
    detectKey: "isZeffy",
  },
  {
    id: "zengo",
    name: "ZenGo",
    shortName: "ZG",
    color: "#FFD700",
    installUrl: "https://zengo.com/",
    detectKey: "isZenGo",
  },
  {
    id: "ownbit",
    name: "Ownbit",
    shortName: "OB",
    color: "#FF6600",
    installUrl: "https://ownbit.io/",
    detectKey: "isOwnbit",
  },

  // ── 71-90 ───────────────────────────────
  {
    id: "zelcore",
    name: "Zelcore",
    shortName: "ZC",
    color: "#2B6CB0",
    installUrl: "https://zelcore.io/",
    detectKey: "isZelcore",
  },
  {
    id: "nabox",
    name: "Nabox Wallet",
    shortName: "NB",
    color: "#3B82F6",
    installUrl: "https://nabox.io/",
    detectKey: "isNabox",
  },
  {
    id: "oblong",
    name: "Oblong",
    shortName: "OL",
    color: "#F472B6",
    installUrl: "https://oblong.finance/",
    detectKey: "isOblong",
  },
  {
    id: "valora",
    name: "Valora",
    shortName: "VL",
    color: "#35BAD2",
    installUrl: "https://valoraapp.com/",
    detectKey: "isValora",
  },
  {
    id: "celowallet",
    name: "Celo Wallet",
    shortName: "CEL",
    color: "#FCFF52",
    installUrl: "https://celo.org/",
    detectKey: "isCeloWallet",
  },
  {
    id: "boba",
    name: "Boba Wallet",
    shortName: "BBA",
    color: "#2D5BE3",
    installUrl: "https://bobanetwork.com/",
    detectKey: "isBoba",
  },
  {
    id: "seq",
    name: "Sequence Wallet",
    shortName: "SQ",
    color: "#4E8CFF",
    installUrl: "https://sequence.app/",
    detectKey: "isSequence",
  },
  {
    id: "ethos",
    name: "Ethos Wallet",
    shortName: "ET",
    color: "#2563EB",
    installUrl: "https://www.ethoswallet.com/",
    detectKey: "isEthos",
  },
  {
    id: "safeheron",
    name: "Safeheron",
    shortName: "SH",
    color: "#1A56DB",
    installUrl: "https://www.safeheron.com/",
    detectKey: "isSafeheron",
  },
  {
    id: "talisman",
    name: "Talisman",
    shortName: "TL",
    color: "#7C3AED",
    installUrl: "https://talisman.xyz/",
    detectKey: "isTalisman",
  },

  // ── 91-110 ──────────────────────────────
  {
    id: "subwallet",
    name: "SubWallet",
    shortName: "SW",
    color: "6B5CE7",
    installUrl: "https://www.subwallet.app/",
    detectKey: "isSubWallet",
  },
  {
    id: "nova",
    name: "Nova Wallet",
    shortName: "NV",
    color: "#FF6B35",
    installUrl: "https://novawallet.io/",
    detectKey: "isNovaWallet",
  },
  {
    id: "polkagate",
    name: "PolkaGate",
    shortName: "PG",
    color: "#E6007A",
    installUrl: "https://polkagate.xyz/",
    detectKey: "isPolkaGate",
  },
  {
    id: "ens",
    name: "ENS Domains",
    shortName: "ENS",
    color: "#5298FF",
    installUrl: "https://ens.domains/",
    detectKey: "isENS",
  },
  {
    id: "opera",
    name: "Opera Crypto",
    shortName: "OC",
    color: "#FF1B2D",
    installUrl: "https://www.opera.com/crypto",
    detectKey: "isOpera",
  },
  {
    id: "status",
    name: "Status Wallet",
    shortName: "ST",
    color: "#6F7CFF",
    installUrl: "https://status.im/",
    detectKey: "isStatus",
  },
  {
    id: "alphawallet",
    name: "AlphaWallet",
    shortName: "AW",
    color: "#FF6B35",
    installUrl: "https://alphawallet.com/",
    detectKey: "isAlphaWallet",
  },
  {
    id: "dydx",
    name: "dYdX Wallet",
    shortName: "dY",
    color: "#6966FF",
    installUrl: "https://dydx.trade/",
    detectKey: "isdYdX",
  },
  {
    id: "binanceweb3",
    name: "Binance Web3 Wallet",
    shortName: "BNB",
    color: "#F0B90B",
    installUrl: "https://www.binance.com/en/web3wallet",
    detectKey: "isBinance",
  },
  {
    id: "derivation",
    name: "Derivation Wallet",
    shortName: "DV",
    color: "#4F46E5",
    installUrl: "https://derivation.com/",
    detectKey: "isDerivation",
  },

  // ── 111-120 ──────────────────────────────
  {
    id: "typo",
    name: "Typo Wallet",
    shortName: "TY",
    color: "#F59E0B",
    installUrl: "https://typo.xyz/",
    detectKey: "isTypo",
  },
  {
    id: "alex",
    name: "Alex Wallet",
    shortName: "ALX",
    color: "#EF4444",
    installUrl: "https://alexlab.co/",
    detectKey: "isAlex",
  },
  {
    id: "xpollinate",
    name: "xPollinate",
    shortName: "XP",
    color: "#10B981",
    installUrl: "https://xpollinate.io/",
    detectKey: "isXPollinate",
  },
  {
    id: "tokenary",
    name: "Tokenary",
    shortName: "TK",
    color: "#5B6CF9",
    installUrl: "https://tokenary.io/",
    detectKey: "isTokenary",
  },
  {
    id: "flux",
    name: "Flux Wallet",
    shortName: "FX",
    color: "#8B5CF6",
    installUrl: "https://zengo.com/flux",
    detectKey: "isFlux",
  },
  {
    id: "uniswap",
    name: "Uniswap Wallet",
    shortName: "UNI",
    color: "#FF007A",
    installUrl: "https://uniswap.org/",
    detectKey: "isUniswapWallet",
  },
  {
    id: "1inch",
    name: "1inch Wallet",
    shortName: "1IN",
    color: "#038BF9",
    installUrl: "https://1inch.io/wallet/",
    detectKey: "is1inchWallet",
  },
  {
    id: "safe",
    name: "Safe (Gnosis Safe)",
    shortName: "SF",
    color: "#12FF80",
    installUrl: "https://safe.global/",
    detectKey: "isSafe",
  },
  {
    id: "ambire",
    name: "Ambire Wallet",
    shortName: "AM",
    color: "#1B1B1B",
    installUrl: "https://www.ambire.com/",
    detectKey: "isAmbire",
  },
  {
    id: "pillow",
    name: "Pillow Wallet",
    shortName: "PL",
    color: "#A78BFA",
    installUrl: "https://pillow.finance/",
    detectKey: "isPillow",
  },

  // ── 121-140 Extra wallets ──────────────
  {
    id: "fireblocks",
    name: "Fireblocks",
    shortName: "FB",
    color: "#FA5020",
    installUrl: "https://www.fireblocks.com/",
    detectKey: "isFireblocks",
  },
  {
    id: "copilot",
    name: "Copilot Wallet",
    shortName: "CPT",
    color: "#8B5CF6",
    installUrl: "https://copilotwallet.xyz/",
    detectKey: "isCopilot",
  },
  {
    id: "binance-wc",
    name: "Binance WalletConnect",
    shortName: "BWC",
    color: "#F0B90B",
    installUrl: "https://www.binance.com",
    detectKey: "isBinanceWC",
  },
  {
    id: "cryptoblades",
    name: "CryptoBlades Wallet",
    shortName: "CBW",
    color: "#FF6B35",
    installUrl: "https://cryptoblades.io/",
    detectKey: "isCryptoBlades",
  },
  {
    id: "airgap",
    name: "AirGap Wallet",
    shortName: "AG",
    color: "#2B6CB0",
    installUrl: "https://airgap.it/",
    detectKey: "isAirGap",
  },
  {
    id: "warden",
    name: "Warden Wallet",
    shortName: "WRD",
    color: "#6D28D9",
    installUrl: "https://wardenprotocol.org/",
    detectKey: "isWarden",
  },
  {
    id: "levana",
    name: "Levana Wallet",
    shortName: "LVN",
    color: "#06B6D4",
    installUrl: "https://levana.finance/",
    detectKey: "isLevana",
  },
  {
    id: "step",
    name: "Step Wallet",
    shortName: "STP",
    color: "#10B981",
    installUrl: "https://step.finance/",
    detectKey: "isStep",
  },
  {
    id: "nami",
    name: "Nami Wallet",
    shortName: "NMI",
    color: "#3B82F6",
    installUrl: "https://namiwallet.io/",
    detectKey: "isNami",
  },
  {
    id: "flint",
    name: "Flint Wallet",
    shortName: "FLT",
    color: "#F59E0B",
    installUrl: "https://flintwallet.io/",
    detectKey: "isFlint",
  },
  {
    id: "nufi",
    name: "NuFi Wallet",
    shortName: "NUF",
    color: "#8B5CF6",
    installUrl: "https://nu.fi/",
    detectKey: "isNuFi",
  },
  {
    id: "eternl",
    name: "Eternl Wallet",
    shortName: "ETL",
    color: "#7C3AED",
    installUrl: "https://eternl.app/",
    detectKey: "isEternl",
  },
  {
    id: "lace",
    name: "Lace Wallet",
    shortName: "LCE",
    color: "#EC4899",
    installUrl: "https://lace.io/",
    detectKey: "isLace",
  },
  {
    id: "yoroi",
    name: "Yoroi Wallet",
    shortName: "YOR",
    color: "#3B82F6",
    installUrl: "https://yoroi-wallet.com/",
    detectKey: "isYoroi",
  },
  {
    id: "minato",
    name: "Minato Wallet",
    shortName: "MNT",
    color: "#EF4444",
    installUrl: "https://minato.finance/",
    detectKey: "isMinato",
  },
  {
    id: "vision",
    name: "Vision Wallet",
    shortName: "VIS",
    color: "#F97316",
    installUrl: "https://visionwallet.io/",
    detectKey: "isVision",
  },
  {
    id: "viawallet",
    name: "ViaWallet",
    shortName: "VIA",
    color: "#2563EB",
    installUrl: "https://viawallet.com/",
    detectKey: "isViaWallet",
  },
  {
    id: "peekaboo",
    name: "Peekaboo Wallet",
    shortName: "PKB",
    color: "#A855F7",
    installUrl: "https://peekaboo.xyz/",
    detectKey: "isPeekaboo",
  },
  {
    id: "safepal",
    name: "SafePal Wallet",
    shortName: "SFP",
    color: "#1E293B",
    installUrl: "https://safepal.io/",
    detectKey: "isSafePal",
  },
  {
    id: "keplr",
    name: "Keplr Wallet",
    shortName: "KPR",
    color: "#6366F1",
    installUrl: "https://www.keplr.app/",
    detectKey: "isKeplr",
  },
  {
    id: "cosmostation",
    name: "CosmoStation",
    shortName: "COS",
    color: "#2F3542",
    installUrl: "https://cosmostation.io/",
    detectKey: "isCosmostation",
  },
  {
    id: "leap",
    name: "Leap Wallet",
    shortName: "LEP",
    color: "#0EA5E9",
    installUrl: "https://leapwallet.io/",
    detectKey: "isLeap",
  },
  {
    id: "xdefiwallet",
    name: "XDC Wallet",
    shortName: "XDC",
    color: "#00B4D8",
    installUrl: "https://xdc.org/",
    detectKey: "isXDCWallet",
  },
  {
    id: "bootloader",
    name: "Bootloader Wallet",
    shortName: "BTL",
    color: "#374151",
    installUrl: "https://bootloader.finance/",
    detectKey: "isBootloader",
  },
  {
    id: "tomo",
    name: "TomoWallet",
    shortName: "TMO",
    color: "#6D28D9",
    installUrl: "https://tomochain.com/",
    detectKey: "isTomo",
  },
  {
    id: "iconex",
    name: "ICONex Wallet",
    shortName: "ICX",
    color: "#131C2E",
    installUrl: "https://iconex.io/",
    detectKey: "isICONex",
  },
  {
    id: "hathor",
    name: "Hathor Wallet",
    shortName: "HTR",
    color: "#FF6B35",
    installUrl: "https://hathor.network/",
    detectKey: "isHathor",
  },
  {
    id: "ninji",
    name: "Ninji Wallet",
    shortName: "NIN",
    color: "#DC2626",
    installUrl: "https://ninji.xyz/",
    detectKey: "isNinji",
  },
  {
    id: "nftgame",
    name: "NFT Game Wallet",
    shortName: "NFG",
    color: "#10B981",
    installUrl: "https://nftgame.app/",
    detectKey: "isNFTGame",
  },
  {
    id: "multiversx",
    name: "MultiversX Wallet",
    shortName: "MX",
    color: "#23F7DD",
    installUrl: "https://multiversx.com/",
    detectKey: "isMultiversX",
  },
  {
    id: "dexalot",
    name: "Dexalot Wallet",
    shortName: "DXA",
    color: "#EF4444",
    installUrl: "https://dexalot.com/",
    detectKey: "isDexalot",
  },
  {
    id: "triangle",
    name: "Triangle Wallet",
    shortName: "TRI",
    color: "#8B5CF6",
    installUrl: "https://triangleplatform.com/",
    detectKey: "isTriangle",
  },
  {
    id: "cryfin",
    name: "Cryfin Wallet",
    shortName: "CRF",
    color: "#0EA5E9",
    installUrl: "https://cryfin.io/",
    detectKey: "isCryfin",
  },
  {
    id: "dcentwallet",
    name: "D’CENT Wallet",
    shortName: "DCT",
    color: "#1E40AF",
    installUrl: "https://dcentwallet.com/",
    detectKey: "isDcent",
  },
  {
    id: "ellipal",
    name: "Ellipal Wallet",
    shortName: "ELP",
    color: "#B91C1C",
    installUrl: "https://www.ellipal.com/",
    detectKey: "isEllipal",
  },
  {
    id: "keystone",
    name: "Keystone Wallet",
    shortName: "KST",
    color: "#0284C7",
    installUrl: "https://keystone.space/",
    detectKey: "isKeystone",
  },
  {
    id: "gridplus",
    name: "GridPlus Wallet",
    shortName: "GPX",
    color: "#059669",
    installUrl: "https://gridplus.io/",
    detectKey: "isGridPlus",
  },
  {
    id: "coolwallet",
    name: "CoolWallet",
    shortName: "CWL",
    color: "#0891B2",
    installUrl: "https://www.coolwallet.io/",
    detectKey: "isCoolWallet",
  },
  {
    id: "prokey",
    name: "ProKey Wallet",
    shortName: "PRK",
    color: "#4338CA",
    installUrl: "https://prokey.io/",
    detectKey: "isProKey",
  },
  {
    id: "archway",
    name: "Archway Wallet",
    shortName: "ARC",
    color: "#7C3AED",
    installUrl: "https://archway.io/",
    detectKey: "isArchway",
  },
  {
    id: "mystic",
    name: "Mystic Wallet",
    shortName: "MYS",
    color: "#DB2777",
    installUrl: "https://mysticwallet.xyz/",
    detectKey: "isMystic",
  },
  {
    id: "vectis",
    name: "Vectis Wallet",
    shortName: "VEC",
    color: "#0EA5E9",
    installUrl: "https://vectis.io/",
    detectKey: "isVectis",
  },
  {
    id: "compass",
    name: "Compass Wallet",
    shortName: "CMP",
    color: "#F59E0B",
    installUrl: "https://compasswallet.io/",
    detectKey: "isCompass",
  },
  {
    id: "vortex",
    name: "Vortex Wallet",
    shortName: "VTX",
    color: "#6366F1",
    installUrl: "https://vortexfinance.io/",
    detectKey: "isVortex",
  },
  {
    id: "aronax",
    name: "Aronax Wallet",
    shortName: "ARN",
    color: "#DC2626",
    installUrl: "https://aronax.io/",
    detectKey: "isAronax",
  },
  {
    id: "magiceden",
    name: "Magic Eden Wallet",
    shortName: "ME",
    color: "#E11D48",
    installUrl: "https://magiceden.io/",
    detectKey: "isMagicEden",
  },
  {
    id: "xdefi2",
    name: "Obrtic Wallet",
    shortName: "OBR",
    color: "#4F46E5",
    installUrl: "https://obrtic.com/",
    detectKey: "isObrtic",
  },
  {
    id: "saturn",
    name: "Saturn Wallet",
    shortName: "SAT",
    color: "#F97316",
    installUrl: "https://saturn.network/",
    detectKey: "isSaturn",
  },
  {
    id: "paraswap",
    name: "ParaSwap Wallet",
    shortName: "PSP",
    color: "#0066FF",
    installUrl: "https://paraswap.io/",
    detectKey: "isParaSwap",
  },
  {
    id: "livewire",
    name: "Livewire Wallet",
    shortName: "LW",
    color: "#22D3EE",
    installUrl: "https://livewirewallet.com/",
    detectKey: "isLivewire",
  },
  {
    id: "rubik",
    name: "Rubik Wallet",
    shortName: "RUB",
    color: "#8B5CF6",
    installUrl: "https://rubik.defi/",
    detectKey: "isRubik",
  },
  {
    id: "bloom",
    name: "Bloom Wallet",
    shortName: "BLM",
    color: "#F472B6",
    installUrl: "https://bloomwallet.io/",
    detectKey: "isBloom",
  },
  {
    id: "guild",
    name: "Guild Wallet",
    shortName: "GLD",
    color: "#10B981",
    installUrl: "https://guild.xyz/",
    detectKey: "isGuild",
  },
  {
    id: "privy",
    name: "Privy Wallet",
    shortName: "PRV",
    color: "#7C3AED",
    installUrl: "https://privy.io/",
    detectKey: "isPrivy",
  },
  {
    id: "particle",
    name: "Particle Wallet",
    shortName: "PRT",
    color: "#0EA5E9",
    installUrl: "https://particle.network/",
    detectKey: "isParticle",
  },
  {
    id: "biconomy",
    name: "Biconomy Wallet",
    shortName: "BCN",
    color: "#FF6B35",
    installUrl: "https://biconomy.io/",
    detectKey: "isBiconomy",
  },
  {
    id: "moralis",
    name: "Moralis Wallet",
    shortName: "MRL",
    color: "#1E293B",
    installUrl: "https://moralis.io/",
    detectKey: "isMoralis",
  },
  {
    id: "web3auth",
    name: "Web3Auth Wallet",
    shortName: "W3A",
    color: "#0369A1",
    installUrl: "https://web3auth.io/",
    detectKey: "isWeb3Auth",
  },
  {
    id: "miden",
    name: "Miden Wallet",
    shortName: "MDN",
    color: "#6D28D9",
    installUrl: "https://miden.io/",
    detectKey: "isMiden",
  },
  {
    id: "spider",
    name: "Spider Wallet",
    shortName: "SPD",
    color: "#DC2626",
    installUrl: "https://spider.defi/",
    detectKey: "isSpider",
  },
  {
    id: "neon",
    name: "Neon Wallet",
    shortName: "NEN",
    color: "#22D3EE",
    installUrl: "https://neon-labs.org/",
    detectKey: "isNeon",
  },
  {
    id: "arcana",
    name: "Arcana Wallet",
    shortName: "ARCN",
    color: "#7C3AED",
    installUrl: "https://arcana.network/",
    detectKey: "isArcana",
  },
  {
    id: "wagmi",
    name: "Wagmi Wallet",
    shortName: "WGM",
    color: "#059669",
    installUrl: "https://wagmi.sh/",
    detectKey: "isWagmiWallet",
  },
  {
    id: "txlab",
    name: "TxLab Wallet",
    shortName: "TXL",
    color: "#0284C7",
    installUrl: "https://txlab.io/",
    detectKey: "isTxLab",
  },
  {
    id: "chainweaver",
    name: "ChainWeaver Wallet",
    shortName: "CWN",
    color: "#1E40AF",
    installUrl: "https://www.chainweaver.org/",
    detectKey: "isChainWeaver",
  },
  {
    id: "kadena",
    name: "Kadena Wallet",
    shortName: "KDA",
    color: "#059669",
    installUrl: "https://www.kadena.io/",
    detectKey: "isKadena",
  },
  {
    id: "zilliqa",
    name: "Zilliqa Wallet",
    shortName: "ZIL",
    color: "#00B4D8",
    installUrl: "https://zilpay.io/",
    detectKey: "isZilliqa",
  },
  {
    id: "moonbeam",
    name: "Moonbeam Wallet",
    shortName: "MBM",
    color: "#56D9FE",
    installUrl: "https://moonbeam.network/",
    detectKey: "isMoonbeam",
  },
  {
    id: "astar",
    name: "Astar Wallet",
    shortName: "AST",
    color: "#7C3AED",
    installUrl: "https://astar.network/",
    detectKey: "isAstar",
  },
  {
    id: "acala",
    name: "Acala Wallet",
    shortName: "ACA",
    color: "#F59E0B",
    installUrl: "https://acala.network/",
    detectKey: "isAcala",
  },
  {
    id: "kintsugi",
    name: "Kintsugi Wallet",
    shortName: "KIN",
    color: "#D97706",
    installUrl: "https://kintsugi.finance/",
    detectKey: "isKintsugi",
  },
  {
    id: "parallel",
    name: "Parallel Wallet",
    shortName: "PAR",
    color: "#6366F1",
    installUrl: "https://parallel.fi/",
    detectKey: "isParallel",
  },
  {
    id: "astarport",
    name: "AstarPortal Wallet",
    shortName: "ASP",
    color: "#8B5CF6",
    installUrl: "https://portal.astar.network/",
    detectKey: "isAstarPortal",
  },
  {
    id: "sesameseed",
    name: "Sesameseed Wallet",
    shortName: "SSD",
    color: "#10B981",
    installUrl: "https://sesameseed.org/",
    detectKey: "isSesameseed",
  },
  {
    id: "beam",
    name: "Beam Wallet",
    shortName: "BEM",
    color: "#F97316",
    installUrl: "https://beam.eco/",
    detectKey: "isBeam",
  },
  {
    id: "fantom",
    name: "Fantom Wallet",
    shortName: "FTM",
    color: "#1969FF",
    installUrl: "https://fantom.foundation/",
    detectKey: "isFantom",
  },
  {
    id: "opera-crypto",
    name: "Opera Crypto Wallet",
    shortName: "OPC",
    color: "#FF1B2D",
    installUrl: "https://www.opera.com/crypto",
    detectKey: "isOperaCrypto",
  },
  {
    id: "brave",
    name: "Brave Wallet",
    shortName: "BRV",
    color: "#FB542B",
    installUrl: "https://brave.com/wallet/",
    detectKey: "isBraveWallet",
  },
  {
    id: "edge",
    name: "Edge Wallet",
    shortName: "EDG",
    color: "#00B4D8",
    installUrl: "https://edge.app/",
    detectKey: "isEdge",
  },
  {
    id: "juggernaut",
    name: "Juggernaut Wallet",
    shortName: "JGN",
    color: "#7C3AED",
    installUrl: "https://jgnetwork.io/",
    detectKey: "isJuggernaut",
  },
  {
    id: "polymesh",
    name: "Polymesh Wallet",
    shortName: "PLY",
    color: "#0EA5E9",
    installUrl: "https://polymesh.network/",
    detectKey: "isPolymesh",
  },
  {
    id: "venly",
    name: "Venly Wallet",
    shortName: "VLY",
    color: "#1E293B",
    installUrl: "https://www.venly.io/",
    detectKey: "isVenly",
  },
  {
    id: "fortmatic",
    name: "Fortmatic Wallet",
    shortName: "FMT",
    color: "#6366F1",
    installUrl: "https://fortmatic.com/",
    detectKey: "isFortmatic",
  },
  {
    id: "portis",
    name: "Portis Wallet",
    shortName: "PRTS",
    color: "#2563EB",
    installUrl: "https://portis.io/",
    detectKey: "isPortis",
  },
  {
    id: "torus",
    name: "Torus Wallet",
    shortName: "TRS",
    color: "#0369A1",
    installUrl: "https://tor.us/",
    detectKey: "isTorus",
  },
  {
    id: "authereum",
    name: "Authereum Wallet",
    shortName: "ATH",
    color: "#059669",
    installUrl: "https://authereum.com/",
    detectKey: "isAuthereum",
  },
  {
    id: "unilogin",
    name: "UniLogin Wallet",
    shortName: "ULG",
    color: "#4F46E5",
    installUrl: "https://unilogin.app/",
    detectKey: "isUniLogin",
  },
  {
    id: "mewconnect",
    name: "MEWconnect",
    shortName: "MWC",
    color: "#F6851B",
    installUrl: "https://www.myetherwallet.com/",
    detectKey: "isMEWconnect",
  },
];

export type DetectedWallet = WalletInfo & {
  installed: boolean;
  provider?: any;
};

/**
 * Escanea window.ethereum y window.ethereum.providers
 * para detectar wallets EVM instaladas como extensiones.
 */
export function detectInstalledWallets(): DetectedWallet[] {
  if (typeof window === "undefined") return [];

  const ethereum = (window as any).ethereum;
  const results: DetectedWallet[] = [];
  const matchedIds = new Set<string>();

  // Recolectar todos los providers disponibles
  const providers: any[] = [];
  if (ethereum) {
    // Si tiene .providers, usar ese array (múltiples wallets)
    if (Array.isArray(ethereum.providers)) {
      providers.push(...ethereum.providers);
    } else {
      providers.push(ethereum);
    }
  }

  // Para cada provider, intentar detectar qué wallet es
  for (const provider of providers) {
    if (!provider) continue;

    for (const wallet of WALLET_REGISTRY) {
      if (matchedIds.has(wallet.id)) continue;

      let detected = false;

      // Detección por propiedad directa (isMetaMask, isTrust, etc.)
      if (wallet.detectKey && provider[wallet.detectKey]) {
        detected = true;
      }

      // Detección por función personalizada
      if (!detected && wallet.detectFn) {
        detected = wallet.detectFn(provider);
      }

      // Detección por providerName
      if (!detected && provider.providerName) {
        const pn = provider.providerName.toLowerCase();
        if (pn.includes(wallet.id) || pn.includes(wallet.name.toLowerCase())) {
          detected = true;
        }
      }

      // Detección por windowKey
      if (!detected && wallet.windowKey && (window as any)[wallet.windowKey]) {
        detected = true;
      }

      if (detected) {
        matchedIds.add(wallet.id);
        results.push({ ...wallet, installed: true, provider });
      }
    }
  }

  // Si no se detectó ninguna wallet pero sí hay ethereum, reportar como genérica
  if (results.length === 0 && ethereum) {
    results.push({
      id: "injected",
      name: ethereum.providerName || "Wallet del navegador",
      shortName: "W",
      color: "#6B7280",
      installUrl: "",
      installed: true,
      provider: ethereum,
    });
  }

  return results;
}

/**
 * Retorna todas las wallets no detectadas con opción de instalar.
 */
export function getNotInstalledWallets(detectedIds: string[]): WalletInfo[] {
  return WALLET_REGISTRY.filter((w) => !detectedIds.includes(w.id));
}
