export interface WalletEntry { id: string; name: string; homepage: string; chromeId?: string; color: string; category: 'extension' | 'mobile' | 'hardware' | 'all'; verified: boolean; }
export function getChromeUrl(c: string) { return `https://chromewebstore.google.com/detail/${c}`; }
export const WALLET_REGISTRY: WalletEntry[] = [
// ===== VERIFIED WALLETS (27) =====
{ id:'metamask', name:'MetaMask', homepage:'https://metamask.io', chromeId:'nkbihfbeogaeaoehlefnkodbefgpgknn', color:'#F6851B', category:'all', verified:true },
{ id:'trust-wallet', name:'Trust Wallet', homepage:'https://trustwallet.com', chromeId:'egjidjbpglichdkebodkjhgpjbjjmlja', color:'#3375BB', category:'all', verified:true },
{ id:'okx-wallet', name:'OKX Wallet', homepage:'https://www.okx.com/web3', chromeId:'mcohilncbfahbmgdjkbpimkcboahcnil', color:'#000000', category:'all', verified:true },
{ id:'coinbase-wallet', name:'Coinbase Wallet', homepage:'https://www.coinbase.com/wallet', chromeId:'hnfanknocnoonbddcjjnifkmbkmgjfhb', color:'#0052FF', category:'all', verified:true },
{ id:'bitget-wallet', name:'Bitget Wallet', homepage:'https://www.bitget.com/wallet', chromeId:'jidiclgjcaakpcolecfjcgpigepjcgnh', color:'#00D4AA', category:'all', verified:true },
{ id:'binance-web3', name:'Binance Web3 Wallet', homepage:'https://www.binance.com/en/web3wallet', chromeId:'fhbohimaelbohpjbbldcngcjlhpmkbmian', color:'#F0B90B', category:'all', verified:true },
{ id:'phantom', name:'Phantom', homepage:'https://phantom.app', chromeId:'bfnaelmomeimhlpmldjndhbobpaeljhf', color:'#AB6BFF', category:'all', verified:true },
{ id:'rabby', name:'Rabby', homepage:'https://rabby.io', chromeId:'acmacodkjbdgmoleebolmdjonilkdbch', color:'#7C5CFC', category:'extension', verified:true },
{ id:'rainbow', name:'Rainbow', homepage:'https://rainbow.me', chromeId:'opglpfjajnmhkbbfohlbgcfpkkjhhodj', color:'#FF0000', category:'all', verified:true },
{ id:'bybit', name:'Bybit Wallet', homepage:'https://www.bybit.com/en/web3', chromeId:'nboeaefgbcflkndcgcllnagdbhkmlfid', color:'#F5A623', category:'all', verified:true },
{ id:'safepal', name:'SafePal', homepage:'https://www.safepal.com', chromeId:'lgmpcpglpngdoalbgeoldeajfclnhafa', color:'#F7931A', category:'all', verified:true },
{ id:'onekey', name:'OneKey', homepage:'https://onekey.so', chromeId:'jbdaocneiihdjggehmicjoeedjlbbhga', color:'#1FC7D4', category:'all', verified:true },
{ id:'mathwallet', name:'MathWallet', homepage:'https://www.mathwallet.org', chromeId:'afbcbjpbpfadlkmhmclhkeeokbmimncb', color:'#00C087', category:'all', verified:true },
{ id:'brave', name:'Brave Wallet', homepage:'https://brave.com/wallet/', color:'#FB542B', category:'extension', verified:true },
{ id:'enkrypt', name:'Enkrypt', homepage:'https://www.enkrypt.com', chromeId:'kkdalkhnhkbhicnfdgjcephdjphiaelad', color:'#1A1A2E', category:'extension', verified:true },
{ id:'coinbase-extension', name:'Coinbase Extension', homepage:'https://www.coinbase.com/wallet/downloads', chromeId:'hnfanknocnoonbddcjjnifkmbkmgjfhb', color:'#0052FF', category:'extension', verified:true },
{ id:'tokenpocket', name:'Token Pocket', homepage:'https://www.tokenpocket.pro', chromeId:'mfgccjchihfkkindfjpjokanfgbncebof', color:'#3B7CFF', category:'all', verified:true },
{ id:'coin98', name:'Coin98 Wallet', homepage:'https://coin98.com/wallet', chromeId:'aeachknmefphepcejbnepoaicjflckfjm', color:'#F7931A', category:'all', verified:true },
{ id:'xdefi', name:'XDEFI Wallet', homepage:'https://www.xdefi.io', chromeId:'hifclbcjcgjimdbglpbljdfkmbgennaag', color:'#1B0A3C', category:'extension', verified:true },
{ id:'frontier', name:'Frontier Wallet', homepage:'https://www.frontier.xyz', chromeId:'fnnegphlobjdhkngcfjldhcbfcnbjifg', color:'#1E90FF', category:'all', verified:true },
{ id:'taho', name:'Taho', homepage:'https://www.taho.xyz', chromeId:'cjnjjbjameggoepjpfmdijlmhdljpofc', color:'#627EEA', category:'extension', verified:true },
{ id:'zerion', name:'Zerion', homepage:'https://zerion.io', chromeId:'hnnkmgmmilpbcfjbhcbckpgkokclgjmbg', color:'#3B68F7', category:'all', verified:true },
{ id:'debank', name:'DeBank', homepage:'https://debank.com', chromeId:'djlcjkkkmjdfjlileglkcjpfhkofpoaa', color:'#4E6EF2', category:'extension', verified:true },
{ id:'frame', name:'Frame', homepage:'https://frame.sh', color:'#222222', category:'extension', verified:true },
{ id:'halo', name:'Halo Wallet', homepage:'https://halo.social', chromeId:'ckagjobjnkchdpnfjkgcblfhgjlbjfha', color:'#7C3AED', category:'extension', verified:true },
{ id:'nabox', name:'Nabox', homepage:'https://nabox.io', chromeId:'ncbfkkbkikgcojhbnmhdikciepfniead', color:'#2563EB', category:'extension', verified:true },
{ id:'solflare', name:'Solflare', homepage:'https://solflare.com', chromeId:'bhhhlbepdkbfbadjbmiofplkjaafjjbg', color:'#FC8C3C', category:'all', verified:true },
// ===== UNVERIFIED WALLETS (278+) =====
// --- Popular DeFi Wallets ---
{ id:'uniswap', name:'Uniswap Wallet', homepage:'https://app.uniswap.org', color:'#FF007A', category:'all', verified:false },
{ id:'oneinch-wallet', name:'1inch Wallet', homepage:'https://1inch.io/wallet', chromeId:'gldnnbhkdbhfnlpmjlhbkkjcjiggmlbe', color:'#1D61B5', category:'all', verified:false },
{ id:'sushiswap', name:'SushiSwap Wallet', homepage:'https://www.sushi.com', color:'#FA52A0', category:'extension', verified:false },
{ id:'curve-wallet', name:'Curve Wallet', homepage:'https://curve.fi', color:'#0000FF', category:'extension', verified:false },
{ id:'aave-wallet', name:'Aave Wallet', homepage:'https://aave.com', color:'#B6509E', category:'extension', verified:false },
{ id:'compound-wallet', name:'Compound Wallet', homepage:'https://compound.finance', color:'#00D395', category:'extension', verified:false },
{ id:'dydx-wallet', name:'dYdX Wallet', homepage:'https://dydx.exchange', color:'#6966FF', category:'extension', verified:false },
{ id:'balancer-wallet', name:'Balancer Wallet', homepage:'https://balancer.fi', color:'#1E1E1E', category:'extension', verified:false },
{ id:'kyber-wallet', name:'KyberSwap Wallet', homepage:'https://kyberswap.com', color:'#2D6BFF', category:'extension', verified:false },
{ id:'paraswap-wallet', name:'ParaSwap Wallet', homepage:'https://paraswap.io', color:'#00D1FF', category:'extension', verified:false },
{ id:'pancakeswap-wallet', name:'PancakeSwap Wallet', homepage:'https://pancakeswap.finance', color:'#D1884F', category:'extension', verified:false },
{ id:'spooky-swap', name:'SpookySwap Wallet', homepage:'https://spookyswap.finance', color:'#D846EF', category:'extension', verified:false },
{ id:'trader-joe', name:'Trader Joe Wallet', homepage:'https://traderjoexyz.com', color:'#E7443B', category:'extension', verified:false },
{ id:'spirit-swap', name:'SpiritSwap Wallet', homepage:'https://spiritswap.finance', color:'#3F3FFF', category:'extension', verified:false },
{ id:'raydium-wallet', name:'Raydium Wallet', homepage:'https://raydium.io', color:'#C200FB', category:'extension', verified:false },
{ id:'alpaca-finance', name:'Alpaca Finance Wallet', homepage:'https://alpacafinance.org', color:'#3B82F6', category:'extension', verified:false },
// --- Solana Wallets ---
{ id:'backpack', name:'Backpack', homepage:'https://backpack.app', color:'#E55353', category:'all', verified:false },
{ id:'slope-wallet', name:'Slope', homepage:'https://slope.finance', color:'#6366F1', category:'all', verified:false },
{ id:'glow-solana', name:'Glow', homepage:'https://glow.app', color:'#F59E0B', category:'mobile', verified:false },
{ id:'magic-eden-wallet', name:'Magic Eden Wallet', homepage:'https://magiceden.io', color:'#E42575', category:'all', verified:false },
{ id:'phantom-sol', name:'Phantom Solana', homepage:'https://phantom.app/solana', color:'#AB6BFF', category:'all', verified:false },
{ id:'sollet', name:'Sollet', homepage:'https://sollet.io', color:'#9945FF', category:'extension', verified:false },
{ id:'coinbase-solana', name:'Coinbase Solana', homepage:'https://www.coinbase.com/wallet', color:'#0052FF', category:'all', verified:false },
{ id:'exodus-solana', name:'Exodus Solana', homepage:'https://www.exodus.com/solana', color:'#2D82B7', category:'all', verified:false },
{ id:'trust-solana', name:'Trust Wallet Solana', homepage:'https://trustwallet.com/solana-wallet', color:'#3375BB', category:'mobile', verified:false },
{ id:'martian-wallet', name:'Martian Wallet', homepage:'https://martianwallet.xyz', color:'#FF6B35', category:'all', verified:false },
{ id:'avalanche-wallet', name:'Core Wallet', homepage:'https://core.app', chromeId:'lfjlgnkapdkocbgdnhopnpcdibkcokheh', color:'#E84142', category:'all', verified:false },
// --- Multi-chain Wallets ---
{ id:'exodus', name:'Exodus', homepage:'https://www.exodus.com', color:'#2D82B7', category:'all', verified:false },
{ id:'guarda-wallet', name:'Guarda Wallet', homepage:'https://guarda.com', color:'#4C6FFF', category:'all', verified:false },
{ id:'coinomi', name:'Coinomi', homepage:'https://www.coinomi.com', color:'#185C37', category:'all', verified:false },
{ id:'jaxx-liberty', name:'Jaxx Liberty', homepage:'https://jaxx.io', color:'#F5A623', category:'all', verified:false },
{ id:'ledger-live', name:'Ledger Live', homepage:'https://www.ledger.com/ledger-live', color:'#000000', category:'all', verified:false },
{ id:'atomic-wallet', name:'Atomic Wallet', homepage:'https://atomicwallet.io', color:'#0E0E2C', category:'all', verified:false },
{ id:'infinito-wallet', name:'Infinito Wallet', homepage:'https://www.infinitowallet.io', color:'#4A90D9', category:'all', verified:false },
{ id:'cobo-wallet', name:'Cobo Wallet', homepage:'https://cobo.com', color:'#1A56DB', category:'all', verified:false },
{ id:'ellipal-wallet', name:'Ellipal Wallet', homepage:'https://www.ellipal.com', color:'#0D47A1', category:'mobile', verified:false },
{ id:'imtoken', name:'imToken', homepage:'https://token.im', color:'#2D6BFF', category:'all', verified:false },
{ id:'huobi-wallet', name:'Huobi Wallet', homepage:'https://www.huobi.com', color:'#2B6CB0', category:'all', verified:false },
{ id:'gate-wallet', name:'Gate.io Wallet', homepage:'https://www.gate.io', color:'#0E7BFF', category:'all', verified:false },
{ id:'kucoin-wallet', name:'KuCoin Wallet', homepage:'https://www.kucoin.com', color:'#23AF91', category:'all', verified:false },
{ id:'crypto-com-wallet', name:'Crypto.com Wallet', homepage:'https://crypto.com/wallet', color:'#002D74', category:'all', verified:false },
{ id:'ngrave-zero', name:'Ngrave Zero', homepage:'https://ngrave.io', color:'#0F172A', category:'hardware', verified:false },
{ id:'coolwallet', name:'CoolWallet', homepage:'https://www.coolwallet.io', color:'#00B4D8', category:'hardware', verified:false },
{ id:'dcent-wallet', name:'D\'Cent Wallet', homepage:'https://dcentwallet.com', color:'#1E3A5F', category:'hardware', verified:false },
{ id:'bitbox02', name:'BitBox02', homepage:'https://shiftcrypto.ch', color:'#1D3557', category:'hardware', verified:false },
{ id:'keepkey', name:'KeepKey', homepage:'https://www.keepkey.com', color:'#4A90D9', category:'hardware', verified:false },
{ id:'securax-wallet', name:'SecuX Wallet', homepage:'https://www.secuxtech.com', color:'#003366', category:'hardware', verified:false },
{ id:'safebox-wallet', name:'SafeBox Wallet', homepage:'https://safebox.io', color:'#1A365D', category:'hardware', verified:false },
{ id:'trezor-suite', name:'Trezor Suite', homepage:'https://trezor.io', color:'#000000', category:'all', verified:false },
{ id:'keystone-wallet', name:'Keystone', homepage:'https://keyst.one', color:'#2D3748', category:'hardware', verified:false },
{ id:'gridplus-wallet', name:'GridPlus', homepage:'https://gridplus.io', color:'#00B8D4', category:'hardware', verified:false },
{ id:'coldcard-wallet', name:'ColdCard', homepage:'https://coldcard.com', color:'#1C1C1C', category:'hardware', verified:false },
{ id:'cipher-browser', name:'Cipher Browser', homepage:'https://cipherbrowser.com', color:'#5B2C6F', category:'extension', verified:false },
{ id:'nifty-wallet', name:'Nifty Wallet', homepage:'https://pigarths.github.io/nifty', color:'#E67E22', category:'extension', verified:false },
{ id:'my-crypto', name:'MyCrypto', homepage:'https://mycrypto.com', color:'#06A4CE', category:'extension', verified:false },
{ id:'portis-wallet', name:'Portis', homepage:'https://portis.io', color:'#363B58', category:'extension', verified:false },
{ id:'fortmatic', name:'Fortmatic', homepage:'https://fortmatic.com', color:'#3B5BDB', category:'extension', verified:false },
{ id:'torus-wallet', name:'Torus', homepage:'https://toruswallet.com', color:'#0364FF', category:'extension', verified:false },
{ id:'authereum', name:'Authereum', homepage:'https://authereum.com', color:'#1A56DB', category:'extension', verified:false },
{ id:'opera-crypto', name:'Opera Crypto', homepage:'https://www.opera.com/crypto', color:'#FF1B2D', category:'extension', verified:false },
{ id:'status-wallet', name:'Status', homepage:'https://status.im', color:'#4747FF', category:'mobile', verified:false },
{ id:'alpha-wallet', name:'AlphaWallet', homepage:'https://alphawallet.com', color:'#2D82B7', category:'mobile', verified:false },
{ id:'infura-wallet', name:'Infura Wallet', homepage:'https://infura.io', color:'#6F42C1', category:'extension', verified:false },
{ id:'web3-onboard', name:'Web3 Onboard', homepage:'https://onboard.blocknative.com', color:'#213147', category:'extension', verified:false },
// --- Cardano Wallets ---
{ id:'nami', name:'Nami', homepage:'https://namiwallet.io', chromeId:'lgpofndjpecmclabckfnhpjplfbpjmgd', color:'#0033AD', category:'extension', verified:false },
{ id:'eternl', name:'Eternl', homepage:'https://eternl.app', chromeId:'kfdpiefjcpjkmffjfmpmohofohpoobkd', color:'#3B82F6', category:'extension', verified:false },
{ id:'yoroi', name:'Yoroi', homepage:'https://yoroi-wallet.com', color:'#0033AD', category:'all', verified:false },
{ id:'flint-wallet', name:'Flint Wallet', homepage:'https://flint-wallet.com', color:'#2563EB', category:'extension', verified:false },
{ id:'gerowallet', name:'GeroWallet', homepage:'https://gerowallet.io', color:'#5B21B6', category:'extension', verified:false },
{ id:'nu-fi', name:'NuFi', homepage:'https://nu.fi', color:'#7C3AED', category:'extension', verified:false },
{ id:'lace-wallet', name:'Lace', homepage:'https://lace.io', color:'#1D4ED8', category:'all', verified:false },
{ id:'typhon-wallet', name:'Typhon Wallet', homepage:'https://typhonwallet.io', color:'#6366F1', category:'extension', verified:false },
{ id:'minswap-wallet', name:'Minswap Wallet', homepage:'https://minswap.org', color:'#F59E0B', category:'extension', verified:false },
// --- Algorand Wallets ---
{ id:'pera-wallet', name:'Pera Wallet', homepage:'https://perawallet.app', color:'#000000', category:'all', verified:false },
{ id:'defly-wallet', name:'Defly Wallet', homepage:'https://defly.app', color:'#3B82F6', category:'mobile', verified:false },
{ id:'algosigner', name:'AlgoSigner', homepage:'https://www.purestake.com/algosigner', color:'#1D3557', category:'extension', verified:false },
{ id:'mnemonic-wallet', name:'Mnemonic Wallet', homepage:'https://www.mnemonic.no', color:'#0F766E', category:'extension', verified:false },
// --- Polkadot / Substrate Wallets ---
{ id:'polkadot-js', name:'Polkadot.js', homepage:'https://polkadot.js.org/extension', chromeId:'jmjgflaahcknocbboamblgccggjdpmja', color:'#E6007A', category:'extension', verified:false },
{ id:'talisman', name:'Talisman', homepage:'https://talisman.xyz', chromeId:'fijngjgcjhjmmpcmkeiomlglpfjjhada', color:'#5E2DBB', category:'extension', verified:false },
{ id:'subwallet', name:'SubWallet', homepage:'https://www.subwallet.app', chromeId:'onhogfjeacbdfojflmcjhlbdihefidhl', color:'#6C47FF', category:'all', verified:false },
{ id:'nova-wallet', name:'Nova Wallet', homepage:'https://novawallet.io', color:'#7C3AED', category:'all', verified:false },
{ id:'enjin-wallet', name:'Enjin Wallet', homepage:'https://enjin.io/wallet', color:'#624DBF', category:'mobile', verified:false },
{ id:'fearless-wallet', name:'Fearless Wallet', homepage:'https://fearlesswallet.io', color:'#FF6B35', category:'all', verified:false },
// --- NEAR Wallets ---
{ id:'near-wallet', name:'NEAR Wallet', homepage:'https://wallet.near.org', color:'#00C08B', category:'all', verified:false },
{ id:'sender-wallet', name:'Sender Wallet', homepage:'https://senderwallet.io', color:'#3B82F6', category:'all', verified:false },
{ id:'meteor-wallet', name:'Meteor Wallet', homepage:'https://meteorwallet.app', color:'#6366F1', category:'all', verified:false },
{ id:'my-near-wallet', name:'MyNearWallet', homepage:'https://mynearwallet.com', color:'#00C08B', category:'extension', verified:false },
{ id:'herewallet', name:'Here Wallet', homepage:'https://herewallet.app', color:'#8B5CF6', category:'mobile', verified:false },
// --- Cosmos Wallets ---
{ id:'keplr-wallet', name:'Keplr', homepage:'https://www.keplr.app', chromeId:'dmkamcknogkgcdfhhbjcokpfgdgplgno', color:'#6F42C1', category:'extension', verified:false },
{ id:'cosmostation', name:'Cosmostation', homepage:'https://www.cosmostation.io', chromeId:'cmmgjljlmkligiojglfnbhkmgmflaplc', color:'#2E3148', category:'all', verified:false },
{ id:'leap-wallet', name:'Leap Wallet', homepage:'https://leapwallet.io', color:'#6C5CE7', category:'all', verified:false },
{ id:'xdefi-cosmos', name:'XDEFI Cosmos', homepage:'https://www.xdefi.io/cosmos', color:'#1B0A3C', category:'extension', verified:false },
{ id:'vstation-wallet', name:'Station Wallet', homepage:'https://station.terra.money', color:'#2C2C3A', category:'extension', verified:false },
{ id:'compass-wallet', name:'Compass Wallet', homepage:'https://compasswallet.io', color:'#1E88E5', category:'all', verified:false },
{ id:'zephyr-wallet', name:'Zephyr Wallet', homepage:'https://zephyrprotocol.com', color:'#0EA5E9', category:'extension', verified:false },
{ id:'nibid-wallet', name:'NIBI Wallet', homepage:'https://nibiru.fi', color:'#4F46E5', category:'extension', verified:false },
// --- Avalanche Wallets ---
{ id:'core-avalanche', name:'Core Wallet', homepage:'https://core.app', chromeId:'lfjlgnkapdkocbgdnhopnpcdibkcokheh', color:'#E84142', category:'all', verified:false },
{ id:'avalanche-wallet-web', name:'Avalanche Web Wallet', homepage:'https://wallet.avax.network', color:'#E84142', category:'extension', verified:false },
{ id:'teleporter-wallet', name:'Teleporter Wallet', homepage:'https://teleporter.avax.network', color:'#D32F2F', category:'extension', verified:false },
{ id:'kalp-wallet', name:'Kalp Wallet', homepage:'https://www.kalp.network', color:'#0284C7', category:'extension', verified:false },
// --- Polygon Wallets ---
{ id:'polygon-wallet', name:'Polygon Wallet', homepage:'https://polygon.technology', color:'#8247E5', category:'extension', verified:false },
{ id:'quickswap-wallet', name:'QuickSwap Wallet', homepage:'https://quickswap.exchange', color:'#3B82F6', category:'extension', verified:false },
{ id:'sushi-polygon', name:'SushiSwap Polygon', homepage:'https://app.sushi.com', color:'#FA52A0', category:'extension', verified:false },
// --- BNB Chain Wallets ---
{ id:'bsc-wallet', name:'BSC Wallet', homepage:'https://www.bnbchain.org', color:'#F0B90B', category:'extension', verified:false },
{ id:'bakery-swap', name:'BakerySwap Wallet', homepage:'https://www.bakeryswap.org', color:'#F5A623', category:'extension', verified:false },
{ id:'apeswap-wallet', name:'ApeSwap Wallet', homepage:'https://apeswap.finance', color:'#6C5CE7', category:'extension', verified:false },
{ id:'wombat-exchange', name:'Wombat Exchange', homepage:'https://wombat.exchange', color:'#F97316', category:'extension', verified:false },
{ id:'thena-wallet', name:'Thena Wallet', homepage:'https://thena.fi', color:'#6D28D9', category:'extension', verified:false },
// --- Arbitrum Wallets ---
{ id:'arbitrum-wallet', name:'Arbitrum Wallet', homepage:'https://arbitrum.io', color:'#2D3748', category:'extension', verified:false },
{ id:'gmx-wallet', name:'GMX Wallet', homepage:'https://gmx.io', color:'#4585FF', category:'extension', verified:false },
{ id:'camelot-wallet', name:'Camelot Wallet', homepage:'https://camelot.exchange', color:'#1E293B', category:'extension', verified:false },
// --- Optimism Wallets ---
{ id:'optimism-wallet', name:'Optimism Wallet', homepage:'https://optimism.io', color:'#FF0420', category:'extension', verified:false },
{ id:'velodrome-wallet', name:'Velodrome Wallet', homepage:'https://app.velodrome.finance', color:'#2563EB', category:'extension', verified:false },
{ id:'sonne-finance', name:'Sonne Finance', homepage:'https://sonne.finance', color:'#7C3AED', category:'extension', verified:false },
// --- zkSync Wallets ---
{ id:'zksync-wallet', name:'zkSync Wallet', homepage:'https://zksync.io', color:'#4F46E5', category:'extension', verified:false },
{ id:'orbiter-wallet', name:'Orbiter Wallet', homepage:'https://www.orbiter.finance', color:'#6366F1', category:'extension', verified:false },
{ id:'mute-wallet', name:'Mute Wallet', homepage:'https://mute.io', color:'#1E3A8A', category:'extension', verified:false },
// --- StarkNet Wallets ---
{ id:'argent-x', name:'Argent X', homepage:'https://www.argent.xyz', chromeId:'dlcobpjiigpikoobohmabehhmhclbbke', color:'#FF6B35', category:'extension', verified:false },
{ id:'braavos-wallet', name:'Braavos', homepage:'https://braavos.app', chromeId:'jffalpoggcpfgohlkecbmjkoihmdjgmgc', color:'#4F46E5', category:'extension', verified:false },
{ id:'mycroft-wallet', name:'Mycroft Wallet', homepage:'https://mycroftwallet.com', color:'#1E40AF', category:'extension', verified:false },
{ id:'aves-wallet', name:'Aves Wallet', homepage:'https://aveswallet.com', color:'#7C3AED', category:'extension', verified:false },
// --- Scroll Wallets ---
{ id:'scroll-wallet', name:'Scroll Wallet', homepage:'https://scroll.io', color:'#FFEFD5', category:'extension', verified:false },
{ id:'skyline-wallet', name:'Skyline Wallet', homepage:'https://skyline.scroll.io', color:'#FDE68A', category:'extension', verified:false },
// --- Base Wallets ---
{ id:'base-wallet', name:'Base Wallet', homepage:'https://base.org', color:'#0052FF', category:'extension', verified:false },
{ id:'aerodrome-wallet', name:'Aerodrome Wallet', homepage:'https://aerodrome.finance', color:'#3B82F6', category:'extension', verified:false },
// --- Linea Wallets ---
{ id:'linea-wallet', name:'Linea Wallet', homepage:'https://linea.build', color:'#61DFFF', category:'extension', verified:false },
// --- Regional / Niche Wallets ---
{ id:'kardiachain-wallet', name:'KardiaChain Wallet', homepage:'https://kardiachain.io', color:'#E74C3C', category:'mobile', verified:false },
{ id:'venly-wallet', name:'Venly', homepage:'https://www.venly.io', chromeId:'amkbmndgnliagdgcopkifdmclhiipiph', color:'#1E88E5', category:'all', verified:false },
{ id:'arcane-wallet', name:'Arcane Wallet', homepage:'https://arcane.is', color:'#6D28D9', category:'extension', verified:false },
{ id:'walleth-wallet', name:'Walleth', homepage:'https://walleth.org', color:'#2E7D32', category:'mobile', verified:false },
{ id:'safemoon-wallet', name:'SafeMoon Wallet', homepage:'https://safemoon.net', color:'#F5A623', category:'mobile', verified:false },
{ id:'everrise-wallet', name:'EverRise Wallet', homepage:'https://everrise.com', color:'#1E88E5', category:'extension', verified:false },
{ id:'rocketx-wallet', name:'RocketX Wallet', homepage:'https://rocketx.exchange', color:'#6C5CE7', category:'all', verified:false },
{ id:'changelly-wallet', name:'Changelly Wallet', homepage:'https://changelly.com', color:'#2E86DE', category:'all', verified:false },
{ id:'guardarian-wallet', name:'Guardarian Wallet', homepage:'https://guardarian.com', color:'#1A56DB', category:'all', verified:false },
{ id:'holo-wallet', name:'Holo Wallet', homepage:'https://holo.host', color:'#FF6B6B', category:'mobile', verified:false },
{ id:'solana-wallet-adapter', name:'Solana Wallet Adapter', homepage:'https://github.com/solana-labs/wallet-adapter', color:'#9945FF', category:'extension', verified:false },
{ id:'trust-earn', name:'Trust Earn Wallet', homepage:'https://trustwallet.com/earn', color:'#3375BB', category:'mobile', verified:false },
{ id:'wallet-connect', name:'WalletConnect', homepage:'https://walletconnect.com', color:'#3B99FC', category:'extension', verified:false },
{ id:'pocket-universe', name:'Pocket Universe', homepage:'https://pocketuniverse.app', chromeId:'cjoeagmlkjdfjailmdaeceocboaffjhl', color:'#7C3AED', category:'extension', verified:false },
{ id:'blowfish-wallet', name:'Blowfish', homepage:'https://blowfish.xyz', chromeId:'jphblfllfgjoclkeklbljjdiccljdgpe', color:'#FF6B6B', category:'extension', verified:false },
{ id:'blockaid', name:'Blockaid', homepage:'https://blockaid.io', color:'#1E3A8A', category:'extension', verified:false },
{ id:'fire-wallet', name:'Fire Wallet', homepage:'https://firewallet.io', color:'#EF4444', category:'extension', verified:false },
{ id:'gem-wallet', name:'Gem Wallet', homepage:'https://gemwallet.com', color:'#3B82F6', category:'all', verified:false },
{ id:'valora-wallet', name:'Valora', homepage:'https://valoraapp.com', color:'#35D07F', category:'mobile', verified:false },
{ id:'celo-wallet', name:'Celo Wallet', homepage:'https://celo.org', color:'#35D07F', category:'mobile', verified:false },
{ id:'morphic-wallet', name:'Morphic', homepage:'https://morphic.app', color:'#8B5CF6', category:'extension', verified:false },
{ id:'privy-wallet', name:'Privy', homepage:'https://privy.io', color:'#1E3A8A', category:'extension', verified:false },
{ id:'biconomy-wallet', name:'Biconomy Wallet', homepage:'https://biconomy.io', color:'#6366F1', category:'extension', verified:false },
{ id:'safe-wallet', name:'Safe Wallet', homepage:'https://safe.global', color:'#12FF80', category:'all', verified:false },
{ id:'gnosis-safe', name:'Gnosis Safe', homepage:'https://gnosis-safe.io', color:'#12FF80', category:'extension', verified:false },
{ id:'ambire-wallet', name:'Ambire Wallet', homepage:'https://www.ambire.com', color:'#1D4ED8', category:'extension', verified:false },
{ id:'pilosa-wallet', name:'Pilosa Wallet', homepage:'https://pilosa.io', color:'#6366F1', category:'extension', verified:false },
{ id:'formatic-wallet', name:'Formatic Wallet', homepage:'https://formatic.com', color:'#3B82F6', category:'extension', verified:false },
{ id:'particle-wallet', name:'Particle Wallet', homepage:'https://particle.network', color:'#6D28D9', category:'extension', verified:false },
{ id:'web3auth-wallet', name:'Web3Auth Wallet', homepage:'https://web3auth.io', color:'#0364FF', category:'extension', verified:false },
{ id:'chain-weaver', name:'ChainWeaver', homepage:'https://www.kadena.io/chainweaver', color:'#00A86B', category:'all', verified:false },
{ id:'zillion-wallet', name:'Zillion Wallet', homepage:'https://zillion.xyz', color:'#7C3AED', category:'extension', verified:false },
{ id:'bob-wallet', name:'Bob Wallet', homepage:'https://bobwallet.io', color:'#F59E0B', category:'extension', verified:false },
{ id:'roundtable-wallet', name:'Roundtable Wallet', homepage:'https://roundtable.finance', color:'#1E3A5F', category:'extension', verified:false },
{ id:'symmetric-wallet', name:'Symmetric Wallet', homepage:'https://symmetric.finance', color:'#6D28D9', category:'extension', verified:false },
{ id:'spookyswap-dex', name:'SpookySwap DEX', homepage:'https://spookyswap.finance', color:'#D846EF', category:'extension', verified:false },
{ id:'spiritswap-dex', name:'SpiritSwap DEX', homepage:'https://spiritswap.finance', color:'#3F3FFF', category:'extension', verified:false },
{ id:'phoenix-wallet', name:'Phoenix Wallet', homepage:'https://phoenixwallet.io', color:'#F97316', category:'mobile', verified:false },
{ id:'zeus-wallet', name:'Zeus Wallet', homepage:'https://zeusln.com', color:'#FFD700', category:'mobile', verified:false },
{ id:'milkroad-wallet', name:'MilkRoad Wallet', homepage:'https://milkroad.io', color:'#2E86DE', category:'extension', verified:false },
{ id:'mezo-wallet', name:'Mezo Wallet', homepage:'https://mezo.network', color:'#1E3A5F', category:'mobile', verified:false },
{ id:'xverse-wallet', name:'Xverse Wallet', homepage:'https://xverse.app', color:'#FF6B35', category:'all', verified:false },
{ id:'hiro-wallet', name:'Hiro Wallet', homepage:'https://hiro.so', color:'#5546FF', category:'all', verified:false },
{ id:'leather-wallet', name:'Leather Wallet', homepage:'https://leather.io', color:'#2D2D2D', category:'extension', verified:false },
{ id:'unisat-wallet', name:'UniSat Wallet', homepage:'https://unisat.io', color:'#F7931A', category:'extension', verified:false },
{ id:'ordinals-wallet', name:'Ordinals Wallet', homepage:'https://ordinalsbot.com', color:'#FF8C00', category:'extension', verified:false },
{ id:'xverse-btc', name:'Xverse BTC', homepage:'https://xverse.app/bitcoin', color:'#FF6B35', category:'all', verified:false },
{ id:'omni-wallet', name:'Omni Wallet', homepage:'https://omni.network', color:'#6366F1', category:'extension', verified:false },
{ id:'fuel-wallet', name:'Fuel Wallet', homepage:'https://fuel.network', color:'#6C5CE7', category:'extension', verified:false },
{ id:'sui-wallet', name:'Sui Wallet', homepage:'https://sui.io', color:'#6FBCF0', category:'all', verified:false },
{ id:'aptos-wallet', name:'Aptos Wallet', homepage:'https://aptosfoundation.org', color:'#2DD8A3', category:'all', verified:false },
{ id:'petra-wallet', name:'Petra Wallet', homepage:'https://petra.app', color:'#3B82F6', category:'extension', verified:false },
{ id:'martian-aptos', name:'Martian Aptos', homepage:'https://martianwallet.xyz', color:'#FF6B35', category:'all', verified:false },
{ id:'fewcha-wallet', name:'Fewcha Wallet', homepage:'https://fewcha.app', color:'#8B5CF6', category:'mobile', verified:false },
{ id:'pontem-wallet', name:'Pontem Wallet', homepage:'https://pontem.network', color:'#6366F1', category:'all', verified:false },
{ id:'hippo-wallet', name:'Hippo Wallet', homepage:'https://hippo-wallet.app', color:'#F59E0B', category:'mobile', verified:false },
{ id:'movr-wallet', name:'Morpho Wallet', homepage:'https://morpho.org', color:'#7C3AED', category:'extension', verified:false },
{ id:'eigenlayer-wallet', name:'EigenLayer Wallet', homepage:'https://eigenlayer.xyz', color:'#1E40AF', category:'extension', verified:false },
{ id:'merkle-wallet', name:'Merkle Wallet', homepage:'https://merkle.io', color:'#059669', category:'extension', verified:false },
{ id:'drift-wallet', name:'Drift Wallet', homepage:'https://drift.trade', color:'#7C3AED', category:'extension', verified:false },
{ id:'jupiter-wallet', name:'Jupiter Wallet', homepage:'https://jup.ag', color:'#65D49A', category:'extension', verified:false },
{ id:'tensor-wallet', name:'Tensor Wallet', homepage:'https://tensor.trade', color:'#3B82F6', category:'extension', verified:false },
{ id:'openrank-wallet', name:'OpenRank Wallet', homepage:'https://openrank.com', color:'#2563EB', category:'extension', verified:false },
{ id:'citadel-wallet', name:'Citadel Wallet', homepage:'https://citadel.one', color:'#1D4ED8', category:'all', verified:false },
{ id:'stakebird-wallet', name:'StakeBird Wallet', homepage:'https://stakebird.com', color:'#F59E0B', category:'extension', verified:false },
{ id:'lido-wallet', name:'Lido Wallet', homepage:'https://stake.lido.fi', color:'#00A3FF', category:'extension', verified:false },
{ id:'rocketpool-wallet', name:'Rocket Pool Wallet', homepage:'https://rocketpool.net', color:'#FF6B35', category:'extension', verified:false },
{ id:'stakewise-wallet', name:'StakeWise Wallet', homepage:'https://stakewise.io', color:'#1E88E5', category:'extension', verified:false },
{ id:'frax-wallet', name:'Frax Wallet', homepage:'https://frax.finance', color:'#000000', category:'extension', verified:false },
{ id:'curve-dao-wallet', name:'Curve DAO Wallet', homepage:'https://www.curve.fi/dao', color:'#0000FF', category:'extension', verified:false },
{ id:'convex-wallet', name:'Convex Wallet', homepage:'https://www.convexfinance.com', color:'#3B82F6', category:'extension', verified:false },
{ id:'yearn-wallet', name:'Yearn Wallet', homepage:'https://yearn.fi', color:'#006AE3', category:'extension', verified:false },
{ id:'harvest-wallet', name:'Harvest Wallet', homepage:'https://harvest.finance', color:'#F5A623', category:'extension', verified:false },
{ id:'pickle-wallet', name:'Pickle Wallet', homepage:'https://pickle.finance', color:'#5B9A2B', category:'extension', verified:false },
{ id:'sushi-trident', name:'Sushi Trident', homepage:'https://www.sushi.com/trident', color:'#FA52A0', category:'extension', verified:false },
{ id:'masa-wallet', name:'Masa Wallet', homepage:'https://www.masa.finance', color:'#7C3AED', category:'extension', verified:false },
{ id:'kroma-wallet', name:'Kroma Wallet', homepage:'https://kroma.network', color:'#2563EB', category:'extension', verified:false },
{ id:'polygon-zk-wallet', name:'Polygon zkEVM Wallet', homepage:'https://polygon.technology/zkevm', color:'#8247E5', category:'extension', verified:false },
{ id:'manta-wallet', name:'Manta Wallet', homepage:'https://manta.network', color:'#1E3A5F', category:'extension', verified:false },
{ id:'taiko-wallet', name:'Taiko Wallet', homepage:'https://taiko.xyz', color:'#E84142', category:'extension', verified:false },
{ id:'risc-zero-wallet', name:'RISC Zero Wallet', homepage:'https://risczero.com', color:'#1E40AF', category:'extension', verified:false },
{ id:'cyber-wallet', name:'Cyber Wallet', homepage:'https://cyber.co', color:'#6C5CE7', category:'extension', verified:false },
{ id:'berachain-wallet', name:'Berachain Wallet', homepage:'https://www.berachain.com', color:'#FF6B35', category:'extension', verified:false },
{ id:'monad-wallet', name:'Monad Wallet', homepage:'https://monad.xyz', color:'#8B5CF6', category:'extension', verified:false },
{ id:'magneto-wallet', name:'Magneto Wallet', homepage:'https://magneto.eco', color:'#EF4444', category:'extension', verified:false },
{ id:'altlayer-wallet', name:'AltLayer Wallet', homepage:'https://altlayer.io', color:'#0EA5E9', category:'extension', verified:false },
{ id:'dymension-wallet', name:'Dymension Wallet', homepage:'https://dymension.xyz', color:'#6366F1', category:'extension', verified:false },
{ id:'celestia-wallet', name:'Celestia Wallet', homepage:'https://celestia.org', color:'#7C3AED', category:'extension', verified:false },
{ id:'avail-wallet', name:'Avail Wallet', homepage:'https://availproject.org', color:'#1E88E5', category:'extension', verified:false },
{ id:'eigen-da-wallet', name:'EigenDA Wallet', homepage:'https://eigen-da.xyz', color:'#1E40AF', category:'extension', verified:false },
{ id:'story-wallet', name:'Story Wallet', homepage:'https://storyprotocol.xyz', color:'#F59E0B', category:'extension', verified:false },
{ id:'plume-wallet', name:'Plume Wallet', homepage:'https://www.plumenetwork.xyz', color:'#2563EB', category:'extension', verified:false },
{ id:'saga-wallet', name:'Saga Wallet', homepage:'https://sagacrypto.com', color:'#6D28D9', category:'extension', verified:false },
{ id:'parallel-wallet', name:'Parallel Wallet', homepage:'https://parallel.fi', color:'#059669', category:'extension', verified:false },
{ id:'acala-wallet', name:'Acala Wallet', homepage:'https://acala.network', color:'#E6007A', category:'extension', verified:false },
{ id:'karura-wallet', name:'Karura Wallet', homepage:'https://karura.network', color:'#FF6B35', category:'extension', verified:false },
{ id:'astar-wallet', name:'Astar Wallet', homepage:'https://astar.network', color:'#6C5CE7', category:'extension', verified:false },
{ id:'shiden-wallet', name:'Shiden Wallet', homepage:'https://shiden.astar.network', color:'#8B5CF6', category:'extension', verified:false },
{ id:'moonbeam-wallet', name:'Moonbeam Wallet', homepage:'https://moonbeam.network', color:'#53CBC8', category:'extension', verified:false },
{ id:'moonriver-wallet', name:'Moonriver Wallet', homepage:'https://moonriver.moonbeam.network', color:'#6C63FF', category:'extension', verified:false },
{ id:'phala-wallet', name:'Phala Wallet', homepage:'https://phala.network', color:'#7C3AED', category:'extension', verified:false },
{ id:'khala-wallet', name:'Khala Wallet', homepage:'https://khala.network', color:'#1E40AF', category:'extension', verified:false },
{ id:'crust-wallet', name:'Crust Wallet', homepage:'https://crust.network', color:'#F59E0B', category:'extension', verified:false },
{ id:'centrifuge-wallet', name:'Centrifuge Wallet', homepage:'https://centrifuge.io', color:'#2D82B7', category:'extension', verified:false },
{ id:'zeitgeist-wallet', name:'Zeitgeist Wallet', homepage:'https://zeitgeist.pm', color:'#6366F1', category:'extension', verified:false },
{ id:'bifrost-wallet', name:'Bifrost Wallet', homepage:'https://bifrost.finance', color:'#3B82F6', category:'extension', verified:false },
{ id:'hydradx-wallet', name:'HydraDX Wallet', homepage:'https://hydradx.io', color:'#EF4444', category:'extension', verified:false },
{ id:'interlay-wallet', name:'Interlay Wallet', homepage:'https://interlay.io', color:'#1E88E5', category:'extension', verified:false },
{ id:'composable-wallet', name:'Composable Wallet', homepage:'https://composable.finance', color:'#7C3AED', category:'extension', verified:false },
{ id:'picasso-wallet', name:'Picasso Wallet', homepage:'https://picasso.paraspell.io', color:'#F59E0B', category:'extension', verified:false },
{ id:'kintsugi-wallet', name:'Kintsugi Wallet', homepage:'https://kintsugi.interlay.io', color:'#D97706', category:'extension', verified:false },
{ id:'robonomics-wallet', name:'Robonomics Wallet', homepage:'https://robonomics.network', color:'#059669', category:'extension', verified:false },
{ id:'subsquid-wallet', name:'Subsquid Wallet', homepage:'https://subsquid.io', color:'#6366F1', category:'extension', verified:false },
{ id:'dolphin-wallet', name:'Dolphin Wallet', homepage:'https://dolphin.io', color:'#0EA5E9', category:'mobile', verified:false },
{ id:'old-pig-wallet', name:'Old Pig Wallet', homepage:'https://oldpig.finance', color:'#F97316', category:'mobile', verified:false },
{ id:'ronin-wallet', name:'Ronin Wallet', homepage:'https://roninchain.com', color:'#1E3A8A', category:'all', verified:false },
{ id:'map-wallet', name:'MAP Wallet', homepage:'https://mapprotocol.io', color:'#2563EB', category:'extension', verified:false },
{ id:'celer-wallet', name:'Celer Wallet', homepage:'https://celer.network', color:'#6C5CE7', category:'extension', verified:false },
{ id:'axelar-wallet', name:'Axelar Wallet', homepage:'https://axelar.network', color:'#3B82F6', category:'extension', verified:false },
{ id:'wormhole-wallet', name:'Wormhole Wallet', homepage:'https://wormhole.com', color:'#6366F1', category:'extension', verified:false },
{ id:'layerzero-wallet', name:'LayerZero Wallet', homepage:'https://layerzero.network', color:'#1E3A5F', category:'extension', verified:false },
{ id:'stargate-wallet', name:'Stargate Wallet', homepage:'https://stargate.finance', color:'#6D28D9', category:'extension', verified:false },
{ id:'across-wallet', name:'Across Wallet', homepage:'https://across.to', color:'#2563EB', category:'extension', verified:false },
{ id:'hop-wallet', name:'Hop Wallet', homepage:'https://hop.exchange', color:'#1D4ED8', category:'extension', verified:false },
{ id:'synapse-wallet', name:'Synapse Wallet', homepage:'https://synapseprotocol.com', color:'#7C3AED', category:'extension', verified:false },
{ id:'nomad-wallet', name:'Nomad Wallet', homepage:'https://nomad.xyz', color:'#059669', category:'extension', verified:false },
{ id:'connext-wallet', name:'Connext Wallet', homepage:'https://connext.network', color:'#3B82F6', category:'extension', verified:false },
{ id:'li-fi-wallet', name:'LI.FI Wallet', homepage:'https://li.fi', color:'#6366F1', category:'extension', verified:false },
{ id:'squid-wallet', name:'Squid Wallet', homepage:'https://squidrouter.com', color:'#F97316', category:'extension', verified:false },
{ id:'routescan-wallet', name:'RouteScan Wallet', homepage:'https://routescan.io', color:'#1E88E5', category:'extension', verified:false },
{ id:'debridge-wallet', name:'deBridge Wallet', homepage:'https://debridge.finance', color:'#7C3AED', category:'extension', verified:false },
{ id:'relay-wallet', name:'Relay Wallet', homepage:'https://relay.link', color:'#2563EB', category:'extension', verified:false },
{ id:'socket-wallet', name:'Socket Wallet', homepage:'https://socket.tech', color:'#6D28D9', category:'extension', verified:false },
{ id:'iwpc-wallet', name:'IWPC Wallet', homepage:'https://iwpc.io', color:'#EF4444', category:'extension', verified:false },
{ id:'swappi-wallet', name:'Swappi Wallet', homepage:'https://swappi.io', color:'#F59E0B', category:'extension', verified:false },
{ id:'parcl-wallet', name:'Parcl Wallet', homepage:'https://parcl.io', color:'#3B82F6', category:'extension', verified:false },
{ id:'synfutures-wallet', name:'SynFutures Wallet', homepage:'https://synfutures.com', color:'#7C3AED', category:'extension', verified:false },
{ id:'polynomial-wallet', name:'Polynomial Wallet', homepage:'https://polynomial.fi', color:'#1E40AF', category:'extension', verified:false },
{ id:'klp-wallet', name:'KLP Wallet', homepage:'https://klp.finance', color:'#F59E0B', category:'extension', verified:false },
{ id:'aevo-wallet', name:'Aevo Wallet', homepage:'https://aevo.xyz', color:'#6366F1', category:'extension', verified:false },
{ id:'lyra-wallet', name:'Lyra Wallet', homepage:'https://lyra.finance', color:'#7C3AED', category:'extension', verified:false },
{ id:'rangers-protocol', name:'Rangers Protocol Wallet', homepage:'https://rangersprotocol.com', color:'#059669', category:'extension', verified:false },
{ id:'venus-protocol', name:'Venus Protocol Wallet', homepage:'https://venus.io', color:'#F5A623', category:'extension', verified:false },
{ id:'alpaca-finance-bsc', name:'Alpaca Finance BSC', homepage:'https://app.alpacafinance.org', color:'#3B82F6', category:'extension', verified:false },
{ id:'ellipsis-wallet', name:'Ellipsis Wallet', homepage:'https://ellipsis.finance', color:'#6366F1', category:'extension', verified:false },
{ id:'beefy-wallet', name:'Beefy Wallet', homepage:'https://beefy.finance', color:'#FF6B35', category:'extension', verified:false },
{ id:'the-graph-wallet', name:'The Graph Wallet', homepage:'https://thegraph.com', color:'#6D28D9', category:'extension', verified:false },
{ id:'aragon-wallet', name:'Aragon Wallet', homepage:'https://aragon.org', color:'#1D4ED8', category:'extension', verified:false },
{ id:'arweave-wallet', name:'Arweave Wallet', homepage:'https://arweave.org', color:'#1E3A5F', category:'extension', verified:false },
{ id:'filecoin-wallet', name:'Filecoin Wallet', homepage:'https://filecoin.io', color:'#0090FF', category:'extension', verified:false },
{ id:'chainlink-wallet', name:'Chainlink Wallet', homepage:'https://chain.link', color:'#375BD2', category:'extension', verified:false },
{ id:'band-protocol', name:'Band Protocol Wallet', homepage:'https://bandprotocol.com', color:'#3B82F6', category:'extension', verified:false },
{ id:'pyth-network', name:'Pyth Network Wallet', homepage:'https://pyth.network', color:'#6D28D9', category:'extension', verified:false },
{ id:'api3-wallet', name:'API3 Wallet', homepage:'https://api3.org', color:'#059669', category:'extension', verified:false },
{ id:'tellor-wallet', name:'Tellor Wallet', homepage:'https://tellor.io', color:'#1E40AF', category:'extension', verified:false },
{ id:'uma-wallet', name:'UMA Wallet', homepage:'https://umaproject.org', color:'#6366F1', category:'extension', verified:false },
{ id:'snapshot-wallet', name:'Snapshot Wallet', homepage:'https://snapshot.org', color:'#7C3AED', category:'extension', verified:false },
{ id:'tally-wallet', name:'Tally Wallet', homepage:'https://tally.cash', color:'#2563EB', category:'extension', verified:false },
{ id:'eth-limo', name:'eth.limo Wallet', homepage:'https://eth.limo', color:'#6366F1', category:'extension', verified:false },
{ id:'ens-wallet', name:'ENS Wallet', homepage:'https://ens.domains', color:'#5298FF', category:'extension', verified:false },
{ id:'lens-protocol', name:'Lens Protocol Wallet', homepage:'https://lens.xyz', color:'#AB6BFF', category:'extension', verified:false },
{ id:'farcaster-wallet', name:'Farcaster Wallet', homepage:'https://farcaster.xyz', color:'#8B5CF6', category:'extension', verified:false },
{ id:'warpcast-wallet', name:'Warpcast Wallet', homepage:'https://warpcast.com', color:'#6366F1', category:'mobile', verified:false },
{ id:'paragraph-wallet', name:'Paragraph Wallet', homepage:'https://paragraph.xyz', color:'#1E40AF', category:'extension', verified:false },
{ id:'mirror-wallet', name:'Mirror Wallet', homepage:'https://mirror.xyz', color:'#2563EB', category:'extension', verified:false },
];
